workspace = { members = [ "execs" ] }
[package]
name = "rnix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fatfs = "0.3"
rand = "0.8.5"
bcrypt = "0.15.0"

